//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarterKit.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarterKit.App_GlobalResources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully created. Please check your inbox to confirm your email.
        /// </summary>
        public static string accountCreated {
            get {
                return ResourceManager.GetString("accountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string codeRequired {
            get {
                return ResourceManager.GetString("codeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your administrator.
        /// </summary>
        public static string defaultError {
            get {
                return ResourceManager.GetString("defaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed. Please now logging.
        /// </summary>
        public static string emailConfirmed {
            get {
                return ResourceManager.GetString("emailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully. We sent you an email to reset your password.
        /// </summary>
        public static string emailConfirmedNeedPassword {
            get {
                return ResourceManager.GetString("emailConfirmedNeedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve entity with id {0}.
        /// </summary>
        public static string entityNotFound {
            get {
                return ResourceManager.GetString("entityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string firstNameRequired {
            get {
                return ResourceManager.GetString("firstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string idRequired {
            get {
                return ResourceManager.GetString("idRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An important exception has been thrown. Thanks for contacting your administrator.
        /// </summary>
        public static string importantException {
            get {
                return ResourceManager.GetString("importantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pass at least one email.
        /// </summary>
        public static string inviteNoEmail {
            get {
                return ResourceManager.GetString("inviteNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users will receive an email to confirm their password.
        /// </summary>
        public static string inviteSuccess {
            get {
                return ResourceManager.GetString("inviteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string lastNameRequired {
            get {
                return ResourceManager.GetString("lastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in.
        /// </summary>
        public static string loggedIn {
            get {
                return ResourceManager.GetString("loggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to confirm your email before you can log in.
        /// </summary>
        public static string loginConfirmEmail {
            get {
                return ResourceManager.GetString("loginConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully updated.
        /// </summary>
        public static string modelUpdateSuccess {
            get {
                return ResourceManager.GetString("modelUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 2 and 6 characters.
        /// </summary>
        public static string passwordLength {
            get {
                return ResourceManager.GetString("passwordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match the password.
        /// </summary>
        public static string passwordMatch {
            get {
                return ResourceManager.GetString("passwordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reseted, please check your email.
        /// </summary>
        public static string passwordReseted {
            get {
                return ResourceManager.GetString("passwordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new code has been sent to you. Please check your email.
        /// </summary>
        public static string resendTwoFactor {
            get {
                return ResourceManager.GetString("resendTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string tenant {
            get {
                return ResourceManager.GetString("tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit an account that you are not part of.
        /// </summary>
        public static string tenantCantEdit {
            get {
                return ResourceManager.GetString("tenantCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is required.
        /// </summary>
        public static string tenantNameRequired {
            get {
                return ResourceManager.GetString("tenantNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 factor authentication is enable, please check your email.
        /// </summary>
        public static string twoFactorEnable {
            get {
                return ResourceManager.GetString("twoFactorEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find user with ID {0}.
        /// </summary>
        public static string userCantRead {
            get {
                return ResourceManager.GetString("userCantRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string userCreated {
            get {
                return ResourceManager.GetString("userCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete your own account.
        /// </summary>
        public static string userDeleteSelf {
            get {
                return ResourceManager.GetString("userDeleteSelf", resourceCulture);
            }
        }
    }
}
